### ISSUE TITLE
Live example is broken

### ISSUE THREAD

**Issue by sskylar** [algolia/jekyll-algolia-example#2]
It looks like the [Live example](https://community.algolia.com/jekyll-algolia-example/) pointed out in the README is no longer working.

In the browser console, I'm seeing:

```js
{name: "AlgoliaSearchError", message: "Invalid Application-ID or API key", debugData: Array(1), statusCode: 403, stack: "AlgoliaSearchError: Invalid Application-ID or API …instantsearch.min.js:2:208145)↵    at <anonymous>"}
```

Any chance you can get this example running again?

**Comment by jensgeffken** [comment]
dang wanted to implement now but nothing works... is this intended ???

**Comment by pixelastic** [comment]
Sorry about that! I accidentally pushed a work in progress (including an API key) in production...

This is now fixed. I have regenerated the API key, and I'm now going to protect the `master` branch for the future :)

Thanks for raising the issue so quickly.

**Comment by jensgeffken** [comment]
algolia rocks
